namenode:
  extends:
    file: hadoop.yml
    service: namenode
  volumes:
    - /tmp/hdfs/namenode:/hdfs

datanode:
  extends:
    file: hadoop.yml
    service: datanode
  volumes:
    - /tmp/hdfs/datanode:/hdfs

resource-manager:
  extends:
    file: spark.yml
    service: resource-manager


spark-master:
  extends:
    file: spark.yml
    service: spark-master
  environment:
    YARN_HEAPSIZE: 2048
    SPARK_MASTER_HOST: spark-master
    PYTHONPATH: /usr/local/spark/dist
    PYSPARK_PYTHON: /usr/bin/python3

spark-worker:
  extends:
    file: spark.yml
    service: spark-worker
  environment:
    PYTHONPATH: /usr/local/spark/dist
    PYSPARK_PYTHON: /usr/bin/python3
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_CORES: 4
    YARN_HEAPSIZE: 2048

job-history:
  extends:
    file: hadoop.yml
    service: job-history

spark-history:
  extends:
    file: spark.yml
    service: spark-history
